// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using example.com.database;

#nullable disable

namespace example.com.database.Migrations.Sqlite
{
    [DbContext(typeof(DataContext))]
    [Migration("20261002124525_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("example.com.database.Entity.Approval", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApproveBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ApproveDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApproveReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApproveStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPending")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ApproveDate", "IsPending", "ApproveStatus");

                    b.ToTable("Approvals");
                });
#pragma warning restore 612, 618
        }
    }
}
